name: todo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Storage
  shared_preferences: ^2.1.0

  #firebase
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0


  #State management
  provider: ^6.0.5

  #Utils
  after_layout: ^1.2.0
  intl: 0.17.0
  time_ago_provider: ^4.2.0

  #UI
  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  country_code_picker: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/font/varela.ttf